-- Esquema inicial complet del projecte. Escrit de forma idempotent
-- (IF NOT EXISTS / comprovacions de tipus existents) perquè és segur
-- executar-lo tant sobre una BBDD buida com sobre una que ja tingui
-- tot això (com la teva).

-- ---------------------------------------------------------------
-- Tipus ENUM
-- ---------------------------------------------------------------

DO $$ BEGIN
    CREATE TYPE camera_status AS ENUM ('pending', 'accepted', 'denied');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE permission_type AS ENUM ('private', 'community', 'public');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE role AS ENUM ('admin', 'user', 'camera_user');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- El pipeline assíncron: fase1 (pendent Model 1/YOLO), fase2 (pendent
-- Model 2/CNN d'espècie), done (processat del tot).
DO $$ BEGIN
    CREATE TYPE status AS ENUM ('fase1', 'fase2', 'done');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ---------------------------------------------------------------
-- Taules
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password_hash character varying(255) NOT NULL,
    mail character varying(255) NOT NULL UNIQUE,
    created_at date DEFAULT CURRENT_DATE NOT NULL,
    role role DEFAULT 'user'::role NOT NULL,
    privacity permission_type DEFAULT 'private'::permission_type NOT NULL
);

CREATE TABLE IF NOT EXISTS camera (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    owner_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    publish_token character varying(255),
    camera_status camera_status DEFAULT 'pending'::camera_status NOT NULL,
    rejection_reason text,
    reviewed_at timestamp without time zone,
    reviewed_by integer REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS community (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL UNIQUE,
    leader_id integer REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS community_member (
    community_id integer NOT NULL REFERENCES community(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (community_id, user_id)
);

CREATE TABLE IF NOT EXISTS camera_community (
    camera_id integer NOT NULL REFERENCES camera(id) ON DELETE CASCADE,
    community_id integer NOT NULL REFERENCES community(id) ON DELETE CASCADE,
    PRIMARY KEY (camera_id, community_id)
);

CREATE TABLE IF NOT EXISTS detection_type (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS detections (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_camera integer REFERENCES camera(id) ON DELETE SET NULL,
    detected_at timestamp without time zone NOT NULL,
    type integer NOT NULL REFERENCES detection_type(id),
    duration integer,
    status status NOT NULL,
    url text,
    user_id integer REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS display (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date date NOT NULL
);

CREATE TABLE IF NOT EXISTS species (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(150) NOT NULL UNIQUE,
    url text NOT NULL
);

CREATE TABLE IF NOT EXISTS species_detected (
    species_id integer NOT NULL REFERENCES species(id),
    detection_id integer NOT NULL REFERENCES detections(id) ON DELETE CASCADE,
    confidence real,
    PRIMARY KEY (species_id, detection_id)
);

-- ---------------------------------------------------------------
-- Dades base imprescindibles perquè els endpoints de deteccions
-- funcionin (busquen aquests tipus pel nom).
-- ---------------------------------------------------------------

-- 'type' no té UNIQUE, així que fem servir WHERE NOT EXISTS en comptes
-- de ON CONFLICT (que no tindria res a on enganxar-se).
INSERT INTO detection_type (type)
    SELECT 'frame_detection'
    WHERE NOT EXISTS (SELECT 1 FROM detection_type WHERE type = 'frame_detection');

INSERT INTO detection_type (type)
    SELECT 'video_detection'
    WHERE NOT EXISTS (SELECT 1 FROM detection_type WHERE type = 'video_detection');
