-- Sembra la taula 'species' amb les 101 especies que reconeix el
-- model de fase 2 (bestgen.pt). Els noms son exactament els que
-- retorna model.names a Ultralytics -- jobs_phase2.py fa el lookup
-- per nom, no per index, per no dependre de l'ordre.
--
-- 'url' (foto de referencia) es queda buida de moment; es pot omplir
-- mes endavant des d'un panell d'administracio o a ma.

INSERT INTO species (name, url) VALUES
    ('Abellerol comu', ''),
    ('Abellerol de Persia', ''),
    ('Aguila marcenca', ''),
    ('Aguila pescadora', ''),
    ('Aligot comu', ''),
    ('Anec collverd', ''),
    ('Anec cullerot', ''),
    ('Arpella palida', ''),
    ('Astor', ''),
    ('Baldriga balear', ''),
    ('Ballester', ''),
    ('Bec de corall senegales', ''),
    ('Bec de serra petit', ''),
    ('Bernat pescaire', ''),
    ('Bitxac comu', ''),
    ('Blauet', ''),
    ('Botxi meridional', ''),
    ('Bruel', ''),
    ('Cadernera europea', ''),
    ('Cames llargues', ''),
    ('Capsigrany', ''),
    ('Cargolet eurasiatic', ''),
    ('Cigne mut', ''),
    ('Colit ros', ''),
    ('Colom roquer', ''),
    ('Corb mari gros', ''),
    ('Cornella negra', ''),
    ('Corriol gros', ''),
    ('Cotorra de Kramer', ''),
    ('Cotorreta pitgrisa', ''),
    ('Cotxa fumada', ''),
    ('Cucut', ''),
    ('Cuereta blanca', ''),
    ('Cuereta torrentera', ''),
    ('Durbec', ''),
    ('Esparver comu', ''),
    ('Estornell comu', ''),
    ('Estornell negre', ''),
    ('Faisa', ''),
    ('Falciot negre', ''),
    ('Falco mostatxut', ''),
    ('Fotja comuna', ''),
    ('Gafarro europeu', ''),
    ('Gaig', ''),
    ('Garsa eurasiatica', ''),
    ('Gavia fosc', ''),
    ('Gavina capnegra americana', ''),
    ('Gratapalles', ''),
    ('Griva', ''),
    ('Lluer eurasiatic', ''),
    ('Mallerenga blava eurasiatica', ''),
    ('Mallerenga carbonera', ''),
    ('Mallerenga cuallarga', ''),
    ('Mallerenga daigua', ''),
    ('Mallerenga emplomallada', ''),
    ('Mallerenga petita', ''),
    ('Martinet blanc', ''),
    ('Martinet ros', ''),
    ('Merla blava', ''),
    ('Merla comuna', ''),
    ('Merla roquera', ''),
    ('Mosquiter comu', ''),
    ('Mussol comu', ''),
    ('Oreneta comuna', ''),
    ('Oreneta cua-regenca', ''),
    ('Oreneta cuablanca comuna', ''),
    ('Oriol', ''),
    ('Papamosques gris', ''),
    ('Pardal comu', ''),
    ('Pardal de bardissa europeu', ''),
    ('Pardal xarrec', ''),
    ('Passerell comu', ''),
    ('Perdiu roja', ''),
    ('Pica-soques blau', ''),
    ('Picot garser gros', ''),
    ('Picot verd comu', ''),
    ('Picot verd iberic', ''),
    ('Pinsa borroner', ''),
    ('Pinsa comu', ''),
    ('Pit-roig', ''),
    ('Piula grossa', ''),
    ('Puput comuna', ''),
    ('Raspinell comu', ''),
    ('Roquerol', ''),
    ('Rossinyol bord', ''),
    ('Rossinyol comu', ''),
    ('Sit negre', ''),
    ('Tallarol capnegre', ''),
    ('Tallarol de casquet', ''),
    ('Territ tresdits', ''),
    ('Territ variant', ''),
    ('Titella', ''),
    ('Tord comu', ''),
    ('Tortora turca', ''),
    ('Trencapinyes', ''),
    ('Trist', ''),
    ('Tudo', ''),
    ('Verdum europeu', ''),
    ('Xarxet comu', ''),
    ('Xatrac becllarg', ''),
    ('Xoriguer comu', '')
ON CONFLICT (name) DO NOTHING;
